ladsph/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.home, name="home"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('menu/', views.menu, name="menu"),
    path('about/', views.about, name="about_us"),
    path('contact/', views.contact, name="contact_us"),

    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),

    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name='logout'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer', null=True, blank=True)
    name = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=15, null=True)

    def __str__(self):
        return str(self.name)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    @property
    def get_absolute_url(self):
        return reverse('', args=[self.slug])

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField()
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    in_stock = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('category',)

    def __str__(self):
        return str(self.name)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping: bool = False
        orderItems = self.orderitem_set.all()
        for i in orderItems:
            if i.product.in_stock:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    housenum = models.CharField(max_length=255, null=True)
    brgy = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    zipcode = models.CharField(max_length=255, null=True)
    shipping_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True)



    def __str__(self):
        return str(self.housenum)

store/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    error_css_class = 'error'
    phone = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'email', 'phone', 'password1', 'password2']

store/views.py
import datetime
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.shortcuts import render, redirect

from .forms import CreateUserForm
from .models import *
from .utils import cartData, guestOrder


def home(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'home.html', context)


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('store:home')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                username = form.cleaned_data.get('username')
                phone = form.cleaned_data.get('phone')
                Customer.objects.create(
                    user=user,
                    name=user.username,
                    phone=phone
                )
                messages.success(request, 'Account was created for ' + username + '!')
                return redirect('store:login')

        context = {'form': form}
        return render(request, 'register.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('store:menu')

    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('store:menu')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('store:login')


def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'cart.html', context)


def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'checkout.html', context)


def categories(request):
    return {
        'categories': Category.objects.all()
    }


def menu(request):
    data = cartData(request)
    cartItems = data['cartItems']

    categories = Category.objects.all()
    products = Product.objects.all().order_by('category')
    pizzas = Product.objects.filter(category__name__contains="Pizza").order_by('price')
    pastas = Product.objects.filter(category__name__contains="Pasta").order_by('price')
    sides = Product.objects.filter(category__name__contains="Sides").order_by('price')
    beverages = Product.objects.filter(category__name__contains="Beverages").order_by('price')
    context = {'products': products, 'cartItems': cartItems, 'categories': categories, 'pizzas': pizzas,
               'pastas': pastas, 'sides': sides, 'beverages': beverages}
    return render(request, 'menu.html', context)


def about(request):
    context = {}
    return render(request, 'about.html', context)


def contact(request):
    context = {}
    return render(request, 'contact.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added.', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()

    if order.shipping:
        ShippingAddress.objects.create(
            transaction_id=transaction_id,
            customer=customer,
            order=order,
            housenum=data['shipping']['housenum'],
            brgy=data['shipping']['brgy'],
            city=data['shipping']['city'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment Complete!', safe=False)

store/templates/cart.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<!--change href in links-->
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:menu' %}">&#x2190; Continue Shopping</a>

            <br>
            <br>

            <table class="table">
                <tr>
                    <th><h5>ITEMS: <strong>{{order.get_cart_items}}</strong></h5></th>
                    <th><h5>TOTAL <strong>₱ {{order.get_cart_total|floatformat:2}}</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px" class="btn btn-success"
                           href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>

            </table>
        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">{{item.product.name}}</div>
                <div style="flex:1">₱{{item.product.price|floatformat:2}}</div>
                <div style="flex:1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}">
                        <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1">₱ {{item.get_total}}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

store/templates/checkout.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Homemade+Apple&family=Kaushan+Script&family=Oswald:wght@200&family=Poppins:wght@200;400;600&display=swap');

    * {
        font-family: 'Poppins', sans-serif;
        font-weight: 400;
    }

    .cod {
        width: 100%;
        border-radius: 20px;
        padding: 7px 0;
        margin-bottom: 7px;
    }
</style>

<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                {% csrf_token %}
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name...">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="phone" name="phone" placeholder="Contact Number...">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <h3>Shipping Address</h3>
                    <hr>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="housenum"
                               placeholder="House/Bldg. No. Street...">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="brgy" placeholder="Barangay...">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="city" placeholder="City...">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="zipcode" placeholder="Zip Code...">
                    </div>

                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                <!--arrange size button Cont.-->
            </form>

        </div>

        <br>
        <div class="box-element hidden" , id="payment-info">
            <hr>
            <h3>Payment Options</h3>
            <hr>
            <label class="radio-container m-r-45">
                <input type="radio" name="radio-pay" value="cod"/> Cash on Delivery (COD)
                <span class="checkmark"></span>
            </label>
            <br>
            <label class="radio-container">
                <input type="radio" name="radio-pay" value="paypal"/> Paypal
                <span class="checkmark"></span>
            </label>

            <br><br>
            <div class="btn btn-success hidden cod" id="cod-payment" onclick="myFunction()">Confirm Payment</div>
            <div class="pp hidden" id="paypal-button-container"></div>
        </div>

    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">{{item.product.name}}</div>
                <div style="flex:1">₱{{item.product.price}}</div>
                <div style="flex:1">{{item.quantity}}</div>
            </div>
            {% endfor %}

            <h5>Items: {{order.get_cart_items}}</h5>
            <h5>Total: ₱{{order.get_cart_total|floatformat:2}}</h5>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://www.paypal.com/sdk/js?client-id=AQK5elv2W9O4OssPD4T2JhW30SuwIMgio13OoMZYxsyveBdUMcjyDiwTPQUco0zmJLJtO6Qa22JalUY9&currency=PHP&disable-funding=card"></script>
<script>
    $(document).ready(function () {
        $("input[type='radio']").click(function () {
            var radioValue = $("input[name='radio-pay']:checked").val();
            if (radioValue === "paypal") {
                document.getElementById('paypal-button-container').classList.remove("hidden");
                document.getElementById('cod-payment').classList.add("hidden");
            } else {
                document.getElementById('cod-payment').classList.remove("hidden");
                document.getElementById('paypal-button-container').classList.add("hidden");
            }
        });
    });
</script>

<script type="text/javascript">
    function myFunction() {
        document.getElementById('cod-payment').addEventListener('click', function (e) {
            submitFormData()
        })
    }
</script>

<script>
    let total = '{{order.get_cart_total}}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: 'blue',
            shape: 'pill',
            label: 'pay',
            height: 40,
        },

        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function (details) {
                submitFormData()
            });
        }


    }).render('#paypal-button-container');
</script>

<script type="text/javascript">
    let shipping = '{{order.shipping}}'

    if (shipping == 'False') {
        document.getElementById('shipping-info').innerHTML = ''
    }

    if (user != 'AnonymousUser') {
        document.getElementById('user-info').innerHTML = ''
    }

    if (shipping == 'False' && user != 'AnonymousUser') {
        document.getElementById('form-wrapper').classList.add("hidden");
        document.getElementById('payment-info').classList.remove("hidden");
    }

    let form = document.getElementById('form')

    csrftoken = form.getElementsByTagName("input")[0].value
    console.log('Newtoken', form.getElementsByTagName("input")[0].value)

    form.addEventListener('submit', function (e) {
        e.preventDefault()
        console.log('Form Submitted!')
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    })

    function submitFormData() {
        console.log('Payment button clicked')

        var userFormData = {
            'name': null,
            'phone': null,
            'total': total,
        }

        var shippingInfo = {
            'housenum': null,
            'brgy': null,
            'city': null,
            'zipcode': null,
        }

        if (shipping != 'False') {
            shippingInfo.housenum = form.housenum.value
            shippingInfo.brgy = form.brgy.value
            shippingInfo.city = form.city.value
            shippingInfo.zipcode = form.zipcode.value
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.phone = form.phone.value
        }

        var url = '/process_order/'
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo}
            )
        })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success', data);
                alert('Transaction completed! Grazie!');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

                window.location.href = "{% url 'store:menu' %}"
            })
    }
</script>

{% endblock content %}

store/templates/home.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>L'Arte dei Sapori</title>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6769035001437123"
     crossorigin="anonymous"></script>

      <link rel="shortcut icon" href="../images/favicon.png" type="image/x-icon">
    <link rel="icon" href="../images/favicon.png" type="image/x-icon">
    <link rel="stylesheet" href="../../../static/css/slicknav.css">

</head>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Homemade+Apple&family=Kaushan+Script&family=Oswald:wght@200&family=Poppins:wght@600&display=swap');

    @keyframes transitionIn {
        from {
            opacity: 0;
            transform: rotateX(-5deg);
        }
        to {
            opacity: 1;
            transform: rotateX(0);
        }
    }

    .banner-area {
        background-image: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)), url("../images/main_bg.gif");
        background-position: center center;
        -webkit-background-size: cover;
        background-size: cover;
        height: 100vh;
    }

    body {
        animation: transitionIn 1s;
        margin: 0;
        padding: 0;
    }

    header {
        padding: 15px 60px;
    }

    .menu {
        margin-top: 30px;
        float: right;
        list-style: none;
    }

    .menu li {
        display: inline-block;
    }

    .menu li a {
        color: #ffffff;
        text-decoration: none;
        padding: 5px 20px;
        font-family: 'Poppins', sans-serif;
        font-size: 18px;
        text-transform: uppercase;
    }

    .menu li a:hover {
        color: #e6ccb3;
        background: #3b3937;
        transition: .3s;
    }

    .logo {
        padding: 20px 0;
        width: 20%;
        float: left;
    }

    .banner-text {
        position: absolute;
        top: 48%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: #ffffff;
        text-align: center;
    }

    .banner-text h2 {
        font-family: baloo;
        margin: 0;
        font-size: 55px;
        color: #ffffff;
    }

    .banner-text p {
        font-size: 22px;
        margin: 0;
        font-family: 'Poppins', sans-serif;
    }

    .banner-text a {
        text-decoration: none;
        border: 1px solid #ffffff;
        font-size: 17px;
        padding: 10px 35px;
        color: white;
        display: inline-block;
        margin-top: 5%;
        margin-right: 10px;
        font-family: 'Poppins', sans-serif;
        text-transform: uppercase;
    }

    .banner-text a:hover {
        border-color: #3b3937;
        background: #3b3937;
        transition: .6s;
        color: #e6ccb3;
    }

    .slicknav_menu {
        display: none;
    }

    @media all and (max-width: 769px) {
        .slicknav_menu {
            margin-right: 10px;
            display: block;
            width: 30%;
            float: right;
            background: transparent;
            font-size: 18px;
            font-family: 'Poppins', sans-serif;
            box-sizing: border-box;
            padding: 5px;
            margin-top: 30px;
        }

        .slicknav_btn {
            background-color: transparent;
            outline: none;
        }

        .slicknav_menu li {
            background: transparent;
            text-transform: uppercase;
            font-size: 14px;
            width: 150px;
            text-align: center;
        }

        .slicknav_menu a:hover {
            color: #e6ccb3;
            background: #3b3937;
            transition: .3s;
        }

        .menu {
            display: none;
        }

        .logo {
            width: 30%;
            float: left;
        }
    }
</style>


<body>

<div class="banner-area">
    <header>
        <a href="{% url 'store:home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="" width="240" height="auto">
        </a>

        <ul class="menu">
            <li><a href="{% url 'store:home' %}">Home</a></li>
            <li><a href="{% url 'store:about_us' %}">About Us</a></li>
            <li><a href="{% url 'store:contact_us' %}">Contact Us</a></li>
        </ul>
    </header>


    <div class="banner-text">
        <img src="{% static 'images/lads_italy.png' %}" alt="" width="100" height="auto">
        <h2>L' Arte dei Sapori</h2>
        <p>Experience Italy at your home</p>
        <a href="{% url 'store:menu' %}">Order</a>
        <a href="{% url 'store:login' %}">Login</a>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="../../../static/js/jquery.slicknav.js"></script>
<script>
    $('.menu').slicknav();
</script>

</body>
</html>

store/templates/login.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

<style>
    @keyframes transitionIn {
        from {
            opacity: 0;
            transform: rotateX(-5deg);
        }
        to {
            opacity: 1;
            transform: rotateX(0);
        }
    }

    .user_card {
        animation: transitionIn 1s;
        width: 350px;
        margin-top: 10%;
        margin-bottom: auto;
        background: #3b3937;
        position: static;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

    }

    .form_container {
        margin-top: 20px;
    }

    #form-title {
        color: #fff;

    }

    .login_btn {
        width: 100%;
        background: #f7ba5b !important;
        color: #3b3937 !important;
        border-radius: 10px;
    }

    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

    .login_container {
        padding: 0 2rem;
    }

    .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }

    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

    #messages {
        background-color: #901B1BFF;
        color: oldlace;
        border-radius: 8px;
        padding: 10px;
        margin-top: 10px;
        margin-bottom: -10px;
        text-align: center;
    }

    .mt-4 {
        color: white;
    }

    .fas {
        height: 27px;
        padding-top: 5px;
    }

</style>

<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>

            </div>
            {% for message in messages %}
            <p id="messages">{{message}}</p>
            {% endfor %}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? &nbsp;<a href="{% url 'store:register' %}" class="ml-2">Sign Up</a>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock content %}